apiVersion: v1
kind: Secret
metadata:
  name: ims-secrets
type: Opaque
data:
  # MONGODB_URI should be a base64 encoded string of your connection URI.
  # Example: echo -n 'mongodb+srv://user:pass@cluster.mongodb.net/test' | base64
  MONGODB_URI: PGI2NC1lbmNvZGVkLXVyaT4=
